In [82]:
# Import Lib
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [83]:
# Load DataSet
data=pd.read_csv('BitcoinPrice.csv')

In [84]:
data.head()

Date  Price
0  07/05/2021   1520
1  08/05/2021   2589
2  09/05/2021   3658
3  10/05/2021   4727
4  11/05/2021   5796

In [85]:
data.tail()

Date   Price
58  04/07/2021  462402
59  05/07/2021  480091
60  06/07/2021  497780
61  07/07/2021  515469
62  08/07/2021  533158

In [86]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Date    63 non-null     object
 1   Price   63 non-null     int64 
dtypes: int64(1), object(1)
memory usage: 1.1+ KB


In [87]:
data.drop(columns=['Date'], inplace=True)

In [88]:
data.head()

Price
0   1520
1   2589
2   3658
3   4727
4   5796

In [89]:
# Predicting 30 days in future
pre_days=30
data['Prediction']=data[['Price']].shift(-pre_days)

In [90]:
data.head()

Price  Prediction
0   1520     33590.0
1   2589     34659.0
2   3658     35728.0
3   4727     36797.0
4   5796     37866.0

In [91]:
data.tail()

Price  Prediction
58  462402         NaN
59  480091         NaN
60  497780         NaN
61  515469         NaN
62  533158         NaN

In [92]:
# Seperate X & Y
X = np.array(data.drop(['Prediction'], axis=1))
X = X[:len(data) - pre_days]

In [93]:
X.shape

(33, 1)

In [94]:
X

array([[ 1520],
       [ 2589],
       [ 3658],
       [ 4727],
       [ 5796],
       [ 6865],
       [ 7934],
       [ 9003],
       [10072],
       [11141],
       [12210],
       [13279],
       [14348],
       [15417],
       [16486],
       [17555],
       [18624],
       [19693],
       [20762],
       [21831],
       [22900],
       [23969],
       [25038],
       [26107],
       [27176],
       [28245],
       [29314],
       [30383],
       [31452],
       [32521],
       [33590],
       [34659],
       [35728]], dtype=int64)

In [95]:
# Create Y as np array
Y = np.array(data['Prediction'])
Y = Y[:-pre_days]

In [96]:
Y.shape

(33,)

In [97]:
Y

array([ 33590.,  34659.,  35728.,  36797.,  37866.,  55555.,  73244.,
        90933., 108622., 126311., 144000., 161689., 179378., 197067.,
       214756., 232445., 250134., 267823., 285512., 303201., 320890.,
       338579., 356268., 373957., 391646., 409335., 427024., 444713.,
       462402., 480091., 497780., 515469., 533158.])

In [98]:
# Split Data

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [99]:
P_days_array=np.array(data.drop(['Prediction'], axis=1))[-pre_days]

In [100]:
print(P_days_array)

[36797]


In [101]:
from sklearn.ensemble import RandomForestRegressor

In [104]:
Rf=RandomForestRegressor(n_estimators=1000,random_state=1)
Rf.fit(X_train,Y_train)
print('Random Forset Accuracy: {: .2f}%'.format(Rf.score(X_test,Y_test)*100))

Random Forset Accuracy:  99.65%


In [105]:
# Prediction
Rf_prediction =Rf.predict(X_test)
print(Rf_prediction)

[470379.739 398173.241  34694.883 439441.678 346326.782 294161.921
 205504.653]


In [107]:
print(Y_test)

[462402. 409335.  34659. 444713. 356268. 303201. 214756.]


In [ ]:
Rf_prediction_30=