In [35]:
# Import Lib
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [36]:
# Load DataSet
data=pd.read_csv('BitcoinPrice.csv')

In [37]:
data.head()

Date        Price
0  2018-08-25 00:00:00  6719.429231
1  2018-08-26 00:00:00  6673.274167
2  2018-08-27 00:00:00  6719.266154
3  2018-08-28 00:00:00  7000.040000
4  2018-08-29 00:00:00  7054.276429

In [38]:
data.tail()

Date         Price
360  2019-08-20 00:00:00  10746.507692
361  2019-08-21 00:00:00  10169.094167
362  2019-08-22 00:00:00  10030.746667
363  2019-08-23 00:00:00  10255.977500
364  2019-08-24 00:00:00  10158.540833

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    365 non-null    object 
 1   Price   365 non-null    float64
dtypes: float64(1), object(1)
memory usage: 5.8+ KB


In [40]:
data.drop(columns=['Date'], inplace=True)

In [41]:
data.head()

Price
0  6719.429231
1  6673.274167
2  6719.266154
3  7000.040000
4  7054.276429

In [42]:
# Predicting 30 days in future
pre_days=30
data['Prediction']=data[['Price']].shift(-pre_days)

In [43]:
data.head()

Price   Prediction
0  6719.429231  6639.304167
1  6673.274167  6412.459167
2  6719.266154  6468.631667
3  7000.040000  6535.476667
4  7054.276429  6677.342500

In [44]:
data.tail()

Price  Prediction
360  10746.507692         NaN
361  10169.094167         NaN
362  10030.746667         NaN
363  10255.977500         NaN
364  10158.540833         NaN

In [45]:
# Seperate X & Y
X = np.array(data.drop(['Prediction'], axis=1))
X = X[:len(data) - pre_days]

In [46]:
X.shape

(335, 1)

In [47]:
X

array([[ 6719.42923077],
       [ 6673.27416667],
       [ 6719.26615385],
       [ 7000.04      ],
       [ 7054.27642857],
       [ 6932.6625    ],
       [ 6981.94615385],
       [ 7100.94666667],
       [ 7247.93538462],
       [ 7260.94923077],
       [ 7326.8525    ],
       [ 7113.06923077],
       [ 6433.27166667],
       [ 6444.80416667],
       [ 6366.1075    ],
       [ 6286.42583333],
       [ 6297.87769231],
       [ 6296.32083333],
       [ 6273.1375    ],
       [ 6450.17923077],
       [ 6499.0625    ],
       [ 6518.655     ],
       [ 6480.64416667],
       [ 6400.60083333],
       [ 6296.63166667],
       [ 6335.82666667],
       [ 6418.56266667],
       [ 6669.99083333],
       [ 6709.3125    ],
       [ 6710.445     ],
       [ 6639.30416667],
       [ 6412.45916667],
       [ 6468.63166667],
       [ 6535.47666667],
       [ 6677.3425    ],
       [ 6550.47416667],
       [ 6593.135     ],
       [ 6590.96833333],
       [ 6562.64166667],
       [ 6470.4025    ],


In [48]:
# Create Y as np array
Y = np.array(data['Prediction'])
Y = Y[:-pre_days]

In [49]:
Y.shape

(335,)

In [50]:
Y

array([ 6639.30416667,  6412.45916667,  6468.63166667,  6535.47666667,
        6677.3425    ,  6550.47416667,  6593.135     ,  6590.96833333,
        6562.64166667,  6470.4025    ,  6563.62833333,  6568.54916667,
        6581.48666667,  6558.5375    ,  6618.56769231,  6621.71166667,
        6563.00916667,  6248.63583333,  6260.53083333,  6260.64583333,
        6299.39916667,  6452.57166667,  6596.61833333,  6596.27615385,
        6568.04076923,  6487.44416667,  6488.82583333,  6531.60166667,
        6498.48583333,  6481.426     ,  6508.31      ,  6478.0825    ,
        6473.75333333,  6465.9175    ,  6448.22166667,  6382.66833333,
        6309.45285714,  6310.28416667,  6342.28083333,  6387.67416667,
        6363.79583333,  6391.87333333,  6436.965     ,  6445.35416667,
        6538.79      ,  6486.25166667,  6411.28083333,  6399.03333333,
        6378.26833333,  6401.93666667,  6372.06333333,  6176.155     ,
        5615.18      ,  5596.1925    ,  5558.24333333,  5606.04416667,
      

In [51]:
# Split Data

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [85]:
P_days_array=np.array(data.drop(['Prediction'], axis=1))[-pre_days:]

In [86]:
print(P_days_array)

[[ 9774.2575    ]
 [ 9725.4025    ]
 [ 9500.32416667]
 [ 9533.97933333]
 [ 9539.7125    ]
 [ 9873.81166667]
 [10088.8       ]
 [10478.90166667]
 [10790.63      ]
 [10826.275     ]
 [11713.16166667]
 [11759.01916667]
 [11703.73833333]
 [11803.88833333]
 [11816.9125    ]
 [11586.1725    ]
 [11377.80416667]
 [11397.80166667]
 [11144.38916667]
 [10450.81333333]
 [ 9988.9475    ]
 [10230.73333333]
 [10292.38333333]
 [10295.1175    ]
 [10605.82583333]
 [10746.50769231]
 [10169.09416667]
 [10030.74666667]
 [10255.9775    ]
 [10158.54083333]]


In [87]:
from sklearn.ensemble import RandomForestRegressor

In [88]:
Rf=RandomForestRegressor(n_estimators=1000,random_state=1)
Rf.fit(X_train,Y_train)
print('Random Forset Accuracy: {: .2f}%'.format(Rf.score(X_test,Y_test)*100))

Random Forset Accuracy:  85.18%


In [89]:
print(X_test)

[[ 6481.426     ]
 [ 3646.34583333]
 [ 3961.49333333]
 [10685.415     ]
 [ 6590.96833333]
 [ 3634.77      ]
 [ 6558.5375    ]
 [ 3468.305     ]
 [ 3813.88      ]
 [ 5214.27666667]
 [ 7896.51083333]
 [10044.11333333]
 [ 3452.32833333]
 [ 7054.27642857]
 [ 3863.33333333]
 [ 5305.275     ]
 [ 3742.94333333]
 [ 4011.0925    ]
 [ 6273.1375    ]
 [ 3656.785     ]
 [ 5031.475     ]
 [11412.12416667]
 [ 3833.31083333]
 [10730.39166667]
 [ 3808.0425    ]
 [ 6639.30416667]
 [ 3498.86833333]
 [ 4980.89833333]
 [ 4116.7775    ]
 [ 6260.53083333]
 [ 6833.35083333]
 [ 3793.26083333]
 [ 3599.84166667]
 [ 3951.565     ]
 [ 5364.99166667]
 [ 7815.13583333]
 [ 3912.28583333]
 [ 5262.36333333]
 [ 6499.0625    ]
 [ 6296.32083333]
 [ 8779.97083333]
 [ 6448.22166667]
 [ 6618.56769231]
 [ 3822.62666667]
 [ 3933.95416667]
 [ 3823.51166667]
 [ 6335.82666667]
 [ 7972.71916667]
 [ 3747.83916667]
 [ 5606.04416667]
 [ 5077.805     ]
 [ 6596.27615385]
 [ 5274.14583333]
 [ 3880.7675    ]
 [ 4145.10846154]
 [ 6486.25

In [90]:
# Prediction
Rf_prediction =Rf.predict(X_test)
print(Rf_prediction)

[ 5901.71217417  3861.13459024  3959.31578167 10002.46048141
  6317.52456536  3760.09443679  6344.83133167  3744.24686865
  3821.0201594   6931.23737583  9949.7883475  10218.32736667
  3837.00826321  6589.62819333  3520.94624058  5603.69318083
  3953.40371716  5116.8907125   6464.55398205  3726.0388344
  5865.28695583 11247.9552825   3689.99461442 10024.53122096
  3904.8137141   6487.17149183  3953.22317032  5766.87356667
  5097.8929375   6424.49927641  6561.68688133  3651.84962827
  3751.16172083  3991.63184141  8158.40839468 12111.3941318
  5032.14534321  7571.46466083  4598.29783333  6554.74494212
 11461.0173675   5655.28620917  6421.74959286  4245.910348
  4267.30935026  4244.97017134  4144.64419968  9131.46158705
  4544.24116466  3807.35928769  7450.08617083  6345.16255202
  8453.81790333  4953.89254577  3904.29695417  5575.92024
  4244.97017134  6201.02906583 11618.31091397  6345.16255202
  5603.69318083  5052.00215571  8454.148135    3721.73956917
 11435.24139135  8073.37129083 

In [91]:
print(Y_test)

[ 4548.7975      3634.77        3865.7975     10605.82583333
  6310.28416667  3881.37923077  6445.35416667  3793.26083333
  3567.29916667  5851.67076923  9791.0175     10030.74666667
  3863.33333333  6677.3425      4980.89833333  7896.51083333
  3868.4875      5114.85416667  6260.53083333  3609.86916667
  7152.48416667 11397.80166667  4034.05666667 10449.62666667
  3632.395       6508.31        3922.615       5718.22916667
  3791.54583333  6378.26833333  7815.13583333  4970.84916667
  3624.15583333  4000.335       8543.03       12668.62916667
  3458.06666667  8641.89166667  6299.39916667  6248.63583333
 12686.38833333  3751.66833333  6538.79        3468.305
  5421.52666667  3813.88        6487.44416667 10748.01166667
  3589.26083333  3567.47        8005.25083333  5596.1925
  7954.80833333  5111.77076923  5310.17333333  3435.34
  3572.735       3920.53666667 10300.4875      5615.18
  7926.705       3548.4275      8033.30666667  4018.04416667
 11411.61666667  7848.41583333  7338.52083333

In [92]:
Y_test.reshape(-1, 1)

array([[ 4548.7975    ],
       [ 3634.77      ],
       [ 3865.7975    ],
       [10605.82583333],
       [ 6310.28416667],
       [ 3881.37923077],
       [ 6445.35416667],
       [ 3793.26083333],
       [ 3567.29916667],
       [ 5851.67076923],
       [ 9791.0175    ],
       [10030.74666667],
       [ 3863.33333333],
       [ 6677.3425    ],
       [ 4980.89833333],
       [ 7896.51083333],
       [ 3868.4875    ],
       [ 5114.85416667],
       [ 6260.53083333],
       [ 3609.86916667],
       [ 7152.48416667],
       [11397.80166667],
       [ 4034.05666667],
       [10449.62666667],
       [ 3632.395     ],
       [ 6508.31      ],
       [ 3922.615     ],
       [ 5718.22916667],
       [ 3791.54583333],
       [ 6378.26833333],
       [ 7815.13583333],
       [ 4970.84916667],
       [ 3624.15583333],
       [ 4000.335     ],
       [ 8543.03      ],
       [12668.62916667],
       [ 3458.06666667],
       [ 8641.89166667],
       [ 6299.39916667],
       [ 6248.63583333],


In [93]:
print(Y_test)

[ 4548.7975      3634.77        3865.7975     10605.82583333
  6310.28416667  3881.37923077  6445.35416667  3793.26083333
  3567.29916667  5851.67076923  9791.0175     10030.74666667
  3863.33333333  6677.3425      4980.89833333  7896.51083333
  3868.4875      5114.85416667  6260.53083333  3609.86916667
  7152.48416667 11397.80166667  4034.05666667 10449.62666667
  3632.395       6508.31        3922.615       5718.22916667
  3791.54583333  6378.26833333  7815.13583333  4970.84916667
  3624.15583333  4000.335       8543.03       12668.62916667
  3458.06666667  8641.89166667  6299.39916667  6248.63583333
 12686.38833333  3751.66833333  6538.79        3468.305
  5421.52666667  3813.88        6487.44416667 10748.01166667
  3589.26083333  3567.47        8005.25083333  5596.1925
  7954.80833333  5111.77076923  5310.17333333  3435.34
  3572.735       3920.53666667 10300.4875      5615.18
  7926.705       3548.4275      8033.30666667  4018.04416667
 11411.61666667  7848.41583333  7338.52083333

In [94]:
#model prediction for 30 days
Rf_prediction_30=Rf.predict(P_days_array)
print(Rf_prediction_30)

[10440.9933425  10317.62604917 10327.5139425  10272.74030917
 10272.74030917 10421.67219583 10233.17275583 10293.130125
 10052.84670596 10070.14776679 10031.40731167 10880.8607185
 10067.76014833 11248.50240633 10260.4036505  11206.11112
 11247.9552825  11247.9552825  10975.13370833 10243.09886167
 10224.71798167 10056.88793853 10063.37085103 10063.37085103
 10446.67757327 10024.53122096 10203.9719425  10218.32736667
 10057.80237853 10231.8693475 ]


In [95]:
#original values 
data.head(30)

Price   Prediction
0   6719.429231  6639.304167
1   6673.274167  6412.459167
2   6719.266154  6468.631667
3   7000.040000  6535.476667
4   7054.276429  6677.342500
5   6932.662500  6550.474167
6   6981.946154  6593.135000
7   7100.946667  6590.968333
8   7247.935385  6562.641667
9   7260.949231  6470.402500
10  7326.852500  6563.628333
11  7113.069231  6568.549167
12  6433.271667  6581.486667
13  6444.804167  6558.537500
14  6366.107500  6618.567692
15  6286.425833  6621.711667
16  6297.877692  6563.009167
17  6296.320833  6248.635833
18  6273.137500  6260.530833
19  6450.179231  6260.645833
20  6499.062500  6299.399167
21  6518.655000  6452.571667
22  6480.644167  6596.618333
23  6400.600833  6596.276154
24  6296.631667  6568.040769
25  6335.826667  6487.444167
26  6418.562667  6488.825833
27  6669.990833  6531.601667
28  6709.312500  6498.485833
29  6710.445000  6481.426000