In [28]:
# task 85

In [29]:
import numpy as np
import pandas as pd
import seaborn as sns

In [30]:
movie=pd.read_csv("movielist.csv")

In [31]:
movie.describe()

AudienceScore  TheatersOpenWeek  OpeningWeekend  BOAvgOpenWeekend  \
count      49.000000         48.000000       49.000000         48.000000   
mean       72.408163       3208.000000       39.783673      11795.875000   
std        12.037993        782.484586       30.031389       6600.083025   
min        47.000000        860.000000        6.500000       2641.000000   
25%        64.000000       2921.500000       21.900000       7596.500000   
50%        73.000000       3390.000000       33.000000      10055.500000   
75%        83.000000       3677.500000       45.300000      12811.500000   
max        91.000000       4362.000000      151.100000      35540.000000   

       DomesticGross  ForeignGross  WorldGross      Budget  Profitability  \
count      49.000000     49.000000   49.000000   49.000000      49.000000   
mean      134.190612    164.390204  298.580204   87.622449     452.997143   
std        81.884008    162.097937  235.719684   64.478237     446.667424   
min        47.850000      0.660000   55.860000    7.500000      99.100000   
25%        66.660000     63.640000  147.880000   33.000000     238.870000   
50%       118.590000     97.340000  202.550000   75.000000     366.250000   
75%       168.270000    215.350000  372.230000  130.000000     516.190000   
max       336.530000    654.000000  963.420000  300.000000    3085.480000   

       OpenProfit  Current Year      Oscar  
count   49.000000     49.000000  49.000000  
mean    63.389796      0.448980   0.469388  
std     53.955310      0.502545   0.504234  
min     12.800000      0.000000   0.000000  
25%     31.330000      0.000000   0.000000  
50%     43.600000      0.000000   0.000000  
75%     76.000000      1.000000   1.000000  
max    317.000000      1.000000   1.000000

In [32]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Movie             49 non-null     object 
 1   AudienceScore     49 non-null     int64  
 2   TheatersOpenWeek  48 non-null     float64
 3   OpeningWeekend    49 non-null     float64
 4   BOAvgOpenWeekend  48 non-null     float64
 5   DomesticGross     49 non-null     float64
 6   ForeignGross      49 non-null     float64
 7   WorldGross        49 non-null     float64
 8   Budget            49 non-null     float64
 9   Profitability     49 non-null     float64
 10  OpenProfit        49 non-null     float64
 11  Current Year      49 non-null     int64  
 12  Oscar             49 non-null     int64  
dtypes: float64(9), int64(3), object(1)
memory usage: 5.1+ KB


In [33]:
movie.head()

Movie  AudienceScore  TheatersOpenWeek  \
0                               Spider-Man 3             54            4252.0   
1                            Shrek the Third             57            4122.0   
2                               Transformers             89            4011.0   
3   Pirates of the Caribbean: At World's End             74            4362.0   
4  Harry Potter and the Order of the Phoenix             82            4285.0   

   OpeningWeekend  BOAvgOpenWeekend  DomesticGross  ForeignGross  WorldGross  \
0           151.1           35540.0         336.53        554.34      890.87   
1           121.6           29507.0         322.72        476.24      798.96   
2            70.5           17577.0         319.25        390.46      709.71   
3           114.7           26302.0         309.42        654.00      963.42   
4            77.1           17998.0         292.00        647.88      939.89   

   Budget  Profitability  OpenProfit  Current Year  Oscar  
0   258.0         345.30       58.57             1      0  
1   160.0         499.35       76.00             0      1  
2   150.0         473.14       47.00             1      0  
3   300.0         321.14       38.23             0      0  
4   150.0         626.59       51.40             1      0

In [34]:
movie.head()

Movie  AudienceScore  TheatersOpenWeek  \
0                               Spider-Man 3             54            4252.0   
1                            Shrek the Third             57            4122.0   
2                               Transformers             89            4011.0   
3   Pirates of the Caribbean: At World's End             74            4362.0   
4  Harry Potter and the Order of the Phoenix             82            4285.0   

   OpeningWeekend  BOAvgOpenWeekend  DomesticGross  ForeignGross  WorldGross  \
0           151.1           35540.0         336.53        554.34      890.87   
1           121.6           29507.0         322.72        476.24      798.96   
2            70.5           17577.0         319.25        390.46      709.71   
3           114.7           26302.0         309.42        654.00      963.42   
4            77.1           17998.0         292.00        647.88      939.89   

   Budget  Profitability  OpenProfit  Current Year  Oscar  
0   258.0         345.30       58.57             1      0  
1   160.0         499.35       76.00             0      1  
2   150.0         473.14       47.00             1      0  
3   300.0         321.14       38.23             0      0  
4   150.0         626.59       51.40             1      0

In [35]:
movie=movie.iloc[:50]

In [36]:
movie=movie.replace({True: 1, False: 0})

In [37]:
movie.head()

Movie  AudienceScore  TheatersOpenWeek  \
0                               Spider-Man 3             54            4252.0   
1                            Shrek the Third             57            4122.0   
2                               Transformers             89            4011.0   
3   Pirates of the Caribbean: At World's End             74            4362.0   
4  Harry Potter and the Order of the Phoenix             82            4285.0   

   OpeningWeekend  BOAvgOpenWeekend  DomesticGross  ForeignGross  WorldGross  \
0           151.1           35540.0         336.53        554.34      890.87   
1           121.6           29507.0         322.72        476.24      798.96   
2            70.5           17577.0         319.25        390.46      709.71   
3           114.7           26302.0         309.42        654.00      963.42   
4            77.1           17998.0         292.00        647.88      939.89   

   Budget  Profitability  OpenProfit  Current Year  Oscar  
0   258.0         345.30       58.57             1      0  
1   160.0         499.35       76.00             0      1  
2   150.0         473.14       47.00             1      0  
3   300.0         321.14       38.23             0      0  
4   150.0         626.59       51.40             1      0

In [38]:
X=movie[['Budget']]

In [39]:
Y=movie[['Oscar']]

In [40]:
X.head()

Budget
0   258.0
1   160.0
2   150.0
3   300.0
4   150.0

In [41]:
Y.head()

Oscar
0      0
1      1
2      0
3      0
4      0

In [42]:
X=X.fillna(0)
Y=Y.fillna(0)

In [43]:
# Train Split

In [44]:
from sklearn.model_selection import train_test_split

In [45]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [46]:
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(39, 1) (10, 1) (39, 1) (10, 1)


In [47]:
from sklearn.linear_model import LogisticRegression

In [48]:
clf_LR=LogisticRegression()

In [49]:
clf_LR.fit(X_train,Y_train)

C:\Users\divya.sunil\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [50]:
Y_test_pred=clf_LR.predict(X_test)

In [51]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [52]:
confusion_matrix(Y_test,Y_test_pred)

array([[4, 3],
       [1, 2]], dtype=int64)

In [53]:
accuracy_score(Y_test,Y_test_pred)

0.6

In [54]:
from sklearn import preprocessing

In [55]:
scaler=preprocessing.StandardScaler().fit(X_train)

In [58]:
X_train_s=scaler.transform(X_train)

In [59]:
X_test_s=scaler.transform(X_test)

In [60]:
X_test_s

array([[-0.43050444],
       [ 0.9388391 ],
       [ 0.33024197],
       [-0.65872837],
       [ 0.9388391 ],
       [-1.19125086],
       [-0.96302693],
       [-1.03910157],
       [ 0.63454053],
       [ 0.9388391 ]])

In [61]:
X_train_s

array([[-0.20228052],
       [-1.00867172],
       [-1.03910157],
       [ 1.3192123 ],
       [-1.03910157],
       [ 0.9388391 ],
       [-0.73480301],
       [ 0.17809269],
       [ 0.78668982],
       [ 0.17809269],
       [-0.05013124],
       [ 0.33024197],
       [-1.11517621],
       [ 0.9388391 ],
       [-0.81087765],
       [-0.27835516],
       [-0.84130751],
       [-0.05013124],
       [ 0.9388391 ],
       [ 0.63454053],
       [ 1.39528694],
       [-1.22928818],
       [-1.13039114],
       [ 1.09098838],
       [ 0.0259434 ],
       [-0.88695229],
       [-0.41528952],
       [ 0.33024197],
       [-0.20228052],
       [-0.20228052],
       [-1.03910157],
       [-0.05013124],
       [-0.3544298 ],
       [-0.05013124],
       [-0.58265373],
       [ 3.22107833],
       [ 2.58205135],
       [-0.96302693],
       [-0.61308358]])

In [62]:
from sklearn.neighbors import KNeighborsClassifier

In [63]:
clf_knn_1=KNeighborsClassifier(n_neighbors=1)

In [64]:
clf_knn_1.fit(X_train_s,Y_train)

C:\Users\divya.sunil\AppData\Local\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=1)

In [65]:
confusion_matrix(Y_test,clf_knn_1.predict(X_test_s))

array([[6, 1],
       [2, 1]], dtype=int64)

In [66]:
accuracy_score(Y_test,clf_knn_1.predict(X_test_s))

0.7

In [67]:
clf_knn_3=KNeighborsClassifier(n_neighbors=3)

In [68]:
clf_knn_3.fit(X_train_s,Y_train)

C:\Users\divya.sunil\AppData\Local\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [70]:
confusion_matrix(Y_test,clf_knn_3.predict(X_test_s))

array([[6, 1],
       [1, 2]], dtype=int64)

In [71]:
accuracy_score(Y_test,clf_knn_3.predict(X_test_s))

0.8

In [72]:
from sklearn.model_selection import GridSearchCV

In [73]:
params={'n_neighbors':[1,2,3,4,5,6,7,8,9,10]}

In [74]:
grid_search_v=GridSearchCV(KNeighborsClassifier(),params)

In [75]:
grid_search_v.fit(X_train_s,Y_train)

C:\Users\divya.sunil\AppData\Local\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\divya.sunil\AppData\Local\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\divya.sunil\AppData\Local\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\divya.sunil\AppData\Local\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [76]:
grid_search_v.best_params_

{'n_neighbors': 10}

In [77]:
optimised_KNN=grid_search_v.best_estimator_

In [78]:
confusion_matrix(Y_test,Y_test_pred)

array([[4, 3],
       [1, 2]], dtype=int64)

In [79]:
accuracy_score(Y_test,Y_test_pred)

0.6