In [6]:
# task 85

In [7]:
import numpy as np
import pandas as pd
import seaborn as sns

In [8]:
movie=pd.read_csv("movielist.csv")

In [9]:
movie.describe()

AudienceScore  TheatersOpenWeek  OpeningWeekend  BOAvgOpenWeekend  \
count      49.000000         48.000000       49.000000         48.000000   
mean       72.408163       3208.000000       39.783673      11795.875000   
std        12.037993        782.484586       30.031389       6600.083025   
min        47.000000        860.000000        6.500000       2641.000000   
25%        64.000000       2921.500000       21.900000       7596.500000   
50%        73.000000       3390.000000       33.000000      10055.500000   
75%        83.000000       3677.500000       45.300000      12811.500000   
max        91.000000       4362.000000      151.100000      35540.000000   

       DomesticGross  ForeignGross  WorldGross      Budget  Profitability  \
count      49.000000     49.000000   49.000000   49.000000      49.000000   
mean      134.190612    164.390204  298.580204   87.622449     452.997143   
std        81.884008    162.097937  235.719684   64.478237     446.667424   
min        47.850000      0.660000   55.860000    7.500000      99.100000   
25%        66.660000     63.640000  147.880000   33.000000     238.870000   
50%       118.590000     97.340000  202.550000   75.000000     366.250000   
75%       168.270000    215.350000  372.230000  130.000000     516.190000   
max       336.530000    654.000000  963.420000  300.000000    3085.480000   

       OpenProfit  Current Year      Oscar  
count   49.000000     49.000000  49.000000  
mean    63.389796      0.448980   0.469388  
std     53.955310      0.502545   0.504234  
min     12.800000      0.000000   0.000000  
25%     31.330000      0.000000   0.000000  
50%     43.600000      0.000000   0.000000  
75%     76.000000      1.000000   1.000000  
max    317.000000      1.000000   1.000000

In [10]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Movie             49 non-null     object 
 1   AudienceScore     49 non-null     int64  
 2   TheatersOpenWeek  48 non-null     float64
 3   OpeningWeekend    49 non-null     float64
 4   BOAvgOpenWeekend  48 non-null     float64
 5   DomesticGross     49 non-null     float64
 6   ForeignGross      49 non-null     float64
 7   WorldGross        49 non-null     float64
 8   Budget            49 non-null     float64
 9   Profitability     49 non-null     float64
 10  OpenProfit        49 non-null     float64
 11  Current Year      49 non-null     int64  
 12  Oscar             49 non-null     int64  
dtypes: float64(9), int64(3), object(1)
memory usage: 5.1+ KB


In [11]:
movie.head()

Movie  AudienceScore  TheatersOpenWeek  \
0                               Spider-Man 3             54            4252.0   
1                            Shrek the Third             57            4122.0   
2                               Transformers             89            4011.0   
3   Pirates of the Caribbean: At World's End             74            4362.0   
4  Harry Potter and the Order of the Phoenix             82            4285.0   

   OpeningWeekend  BOAvgOpenWeekend  DomesticGross  ForeignGross  WorldGross  \
0           151.1           35540.0         336.53        554.34      890.87   
1           121.6           29507.0         322.72        476.24      798.96   
2            70.5           17577.0         319.25        390.46      709.71   
3           114.7           26302.0         309.42        654.00      963.42   
4            77.1           17998.0         292.00        647.88      939.89   

   Budget  Profitability  OpenProfit  Current Year  Oscar  
0   258.0         345.30       58.57             1      0  
1   160.0         499.35       76.00             0      1  
2   150.0         473.14       47.00             1      0  
3   300.0         321.14       38.23             0      0  
4   150.0         626.59       51.40             1      0

In [12]:
movie.head()

Movie  AudienceScore  TheatersOpenWeek  \
0                               Spider-Man 3             54            4252.0   
1                            Shrek the Third             57            4122.0   
2                               Transformers             89            4011.0   
3   Pirates of the Caribbean: At World's End             74            4362.0   
4  Harry Potter and the Order of the Phoenix             82            4285.0   

   OpeningWeekend  BOAvgOpenWeekend  DomesticGross  ForeignGross  WorldGross  \
0           151.1           35540.0         336.53        554.34      890.87   
1           121.6           29507.0         322.72        476.24      798.96   
2            70.5           17577.0         319.25        390.46      709.71   
3           114.7           26302.0         309.42        654.00      963.42   
4            77.1           17998.0         292.00        647.88      939.89   

   Budget  Profitability  OpenProfit  Current Year  Oscar  
0   258.0         345.30       58.57             1      0  
1   160.0         499.35       76.00             0      1  
2   150.0         473.14       47.00             1      0  
3   300.0         321.14       38.23             0      0  
4   150.0         626.59       51.40             1      0

In [13]:
movie=movie.iloc[:50]

In [14]:
movie=movie.replace({True: 1, False: 0})

In [15]:
movie.head()

Movie  AudienceScore  TheatersOpenWeek  \
0                               Spider-Man 3             54            4252.0   
1                            Shrek the Third             57            4122.0   
2                               Transformers             89            4011.0   
3   Pirates of the Caribbean: At World's End             74            4362.0   
4  Harry Potter and the Order of the Phoenix             82            4285.0   

   OpeningWeekend  BOAvgOpenWeekend  DomesticGross  ForeignGross  WorldGross  \
0           151.1           35540.0         336.53        554.34      890.87   
1           121.6           29507.0         322.72        476.24      798.96   
2            70.5           17577.0         319.25        390.46      709.71   
3           114.7           26302.0         309.42        654.00      963.42   
4            77.1           17998.0         292.00        647.88      939.89   

   Budget  Profitability  OpenProfit  Current Year  Oscar  
0   258.0         345.30       58.57             1      0  
1   160.0         499.35       76.00             0      1  
2   150.0         473.14       47.00             1      0  
3   300.0         321.14       38.23             0      0  
4   150.0         626.59       51.40             1      0

In [16]:
X=movie[['Budget']]

In [17]:
Y=movie[['Oscar']]

In [18]:
X.head()

Budget
0   258.0
1   160.0
2   150.0
3   300.0
4   150.0

In [19]:
Y.head()

Oscar
0      0
1      1
2      0
3      0
4      0

In [20]:
X=X.fillna(0)
Y=Y.fillna(0)

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
clfs_lrs=LogisticRegression()

In [23]:
clfs_lrs.fit(X,Y)

C:\Users\divya.sunil\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [24]:
clfs_lrs.coef_

array([[-0.00555668]])

In [25]:
clfs_lrs.intercept_

array([0.35708087])

In [26]:
import statsmodels.api as sn

In [27]:
X_const=sn.add_constant(X)

In [28]:
X_const.head()

const  Budget
0    1.0   258.0
1    1.0   160.0
2    1.0   150.0
3    1.0   300.0
4    1.0   150.0

In [29]:
import statsmodels.discrete.discrete_model as sm

In [30]:
logit = sm.Logit(Y,X_const).fit()

Optimization terminated successfully.
         Current function value: 0.676749
         Iterations 4


In [31]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                  Oscar   No. Observations:                   49
Model:                          Logit   Df Residuals:                       47
Method:                           MLE   Df Model:                            1
Date:                Wed, 08 May 2024   Pseudo R-squ.:                 0.02101
Time:                        15:28:40   Log-Likelihood:                -33.161
converged:                       True   LL-Null:                       -33.872
Covariance Type:            nonrobust   LLR p-value:                    0.2329
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.3571      0.500      0.714      0.475      -0.623       1.337
Budget        -0.0056      0.005     -1.155      0.248      -0.015       0.004
==============================================================================
"""

In [32]:
# Perdicting & Confusion Matrix

In [33]:
clfs_lrs.predict_proba(X)

array([[0.74583896, 0.25416104],
       [0.62994651, 0.37005349],
       [0.61690229, 0.38309771],
       [0.78750011, 0.21249989],
       [0.61690229, 0.38309771],
       [0.61690229, 0.38309771],
       [0.56319856, 0.43680144],
       [0.59031968, 0.40968032],
       [0.50797094, 0.49202906],
       [0.50102577, 0.49897423],
       [0.61690229, 0.38309771],
       [0.51491304, 0.48508696],
       [0.53569418, 0.46430582],
       [0.45668124, 0.54331876],
       [0.4217958 , 0.5782042 ],
       [0.60368754, 0.39631246],
       [0.56319856, 0.43680144],
       [0.59031968, 0.40968032],
       [0.54948417, 0.45051583],
       [0.52877732, 0.47122268],
       [0.61690229, 0.38309771],
       [0.43882125, 0.56117875],
       [0.52877732, 0.47122268],
       [0.51491304, 0.48508696],
       [0.49546922, 0.50453078],
       [0.52877732, 0.47122268],
       [0.56319856, 0.43680144],
       [0.64915739, 0.35084261],
       [0.54948417, 0.45051583],
       [0.4940802 , 0.5059198 ],
       [0.

In [34]:
y_pred=clfs_lrs.predict(X)

In [35]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1], dtype=int64)

In [36]:
y_pred_03=(clfs_lrs.predict_proba(X)[:1]>=0.3).astype(bool)

In [37]:
y_pred_03

array([[ True, False]])

In [38]:
from sklearn.metrics import confusion_matrix

In [39]:
confusion_matrix(Y,y_pred)

array([[15, 11],
       [14,  9]], dtype=int64)

In [40]:
# LDA

In [41]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [42]:
clf_lda=LinearDiscriminantAnalysis()

In [43]:
clf_lda.fit(X,Y)

C:\Users\divya.sunil\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearDiscriminantAnalysis()

In [44]:
y_pred_lda=clf_lda.predict(X)

In [45]:
y_pred_lda

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1], dtype=int64)

In [46]:
clf_lda.predict_proba(X)

array([[0.73372709, 0.26627291],
       [0.62318343, 0.37681657],
       [0.61087393, 0.38912607],
       [0.77424101, 0.22575899],
       [0.61087393, 0.38912607],
       [0.61087393, 0.38912607],
       [0.56035586, 0.43964414],
       [0.5858406 , 0.4141594 ],
       [0.50855557, 0.49144443],
       [0.50204449, 0.49795551],
       [0.61087393, 0.38912607],
       [0.51506374, 0.48493626],
       [0.53454886, 0.46545114],
       [0.46045113, 0.53954887],
       [0.42766865, 0.57233135],
       [0.59842142, 0.40157858],
       [0.56035586, 0.43964414],
       [0.5858406 , 0.4141594 ],
       [0.54748427, 0.45251573],
       [0.52806258, 0.47193742],
       [0.61087393, 0.38912607],
       [0.44367745, 0.55632255],
       [0.52806258, 0.47193742],
       [0.51506374, 0.48493626],
       [0.49683502, 0.50316498],
       [0.52806258, 0.47193742],
       [0.56035586, 0.43964414],
       [0.64134928, 0.35865072],
       [0.54748427, 0.45251573],
       [0.49553272, 0.50446728],
       [0.

In [47]:
from sklearn.metrics import confusion_matrix

In [48]:
confusion_matrix(Y,y_pred_lda)

array([[15, 11],
       [14,  9]], dtype=int64)

In [49]:
confusion_matrix(Y,y_pred)

array([[15, 11],
       [14,  9]], dtype=int64)

In [50]:
# same

In [51]:
# Train Split

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [54]:
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(39, 1) (10, 1) (39, 1) (10, 1)


In [55]:
clf_LR=LogisticRegression()

In [56]:
clf_LR.fit(X_train,Y_train)

C:\Users\divya.sunil\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [57]:
Y_test_pred=clf_LR.predict(X_test)

In [58]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [59]:
confusion_matrix(Y_test,Y_test_pred)

array([[4, 3],
       [1, 2]], dtype=int64)

In [60]:
accuracy_score(Y_test,Y_test_pred)

0.6