In [107]:
import numpy as np
import pandas as pd
import seaborn as sns

In [108]:
data=pd.read_csv("housesale.csv")

In [109]:
data.head()

price  resid_area  air_qual  dist1  dist2  dist3  dist4  teachers  \
0   24.0       32.31     0.589      2      2      2    2.0        24   
1   21.6       37.07     0.532      4      2      3    3.0        24   
2   34.7       37.07     0.425      3      2      1    1.0        24   
3   33.4       37.07     0.485      3      2      3    3.0        24   
4   36.9       37.07     0.564      3      3      3    3.0        24   

   poor_prop airport  n_hos_beds  n_hot_rooms waterbody  rainfall bus_ter  \
0        4.5      No       18.30       11.120     River        23      No   
1        9.2      No       17.84       12.178      Lake        42     Yes   
2        5.6      No       17.37       12.200       NaN        39      No   
3        7.2      No        8.60       10.200      Lake        56      No   
4        4.5      No        8.60       10.740      Lake        45     Yes   

    parks  Sold  
0  0.0500     0  
1  0.0469     1  
2  0.0438     0  
3  0.0407     0  
4  0.0376     0

In [110]:
X=data[['price']]

In [111]:
Y=data[['Sold']]

In [112]:
X.head()

price
0   24.0
1   21.6
2   34.7
3   33.4
4   36.9

In [113]:
Y.head()

Sold
0     0
1     1
2     0
3     0
4     0

In [114]:
from sklearn.linear_model import LogisticRegression

In [115]:
clfs_lrs=LogisticRegression()

In [116]:
clfs_lrs.fit(X,Y)

C:\Users\divya.sunil\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [117]:
clfs_lrs.coef_

array([[-0.04267495]])

In [118]:
clfs_lrs.intercept_

array([0.84827951])

In [119]:
import statsmodels.api as sn

In [120]:
X_const=sn.add_constant(X)

In [121]:
X_const.head()

const  price
0    1.0   24.0
1    1.0   21.6
2    1.0   34.7
3    1.0   33.4
4    1.0   36.9

In [122]:
import statsmodels.discrete.discrete_model as sm

In [123]:
logit = sm.Logit(Y,X_const).fit()

Optimization terminated successfully.
         Current function value: 0.679769
         Iterations 4


In [124]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  100
Model:                          Logit   Df Residuals:                       98
Method:                           MLE   Df Model:                            1
Date:                Tue, 07 May 2024   Pseudo R-squ.:                 0.01475
Time:                        12:13:36   Log-Likelihood:                -67.977
converged:                       True   LL-Null:                       -68.994
Covariance Type:            nonrobust   LLR p-value:                    0.1537
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.8492      0.742      1.144      0.253      -0.606       2.304
price         -0.0427      0.030     -1.407      0.160      -0.102       0.017
==============================================================================
"""

In [133]:
data = pd.get_dummies(data)

In [134]:
data = dummy_movie.replace({True: 0, False: 1})

In [135]:
data.head()

price  resid_area  air_qual  dist1  dist2  dist3  dist4  teachers  \
0   24.0       32.31     0.589      2      2      2    2.0        24   
1   21.6       37.07     0.532      4      2      3    3.0        24   
2   34.7       37.07     0.425      3      2      1    1.0        24   
3   33.4       37.07     0.485      3      2      3    3.0        24   
4   36.9       37.07     0.564      3      3      3    3.0        24   

   poor_prop  n_hos_beds  ...  rainfall   parks  Sold  airport_No  \
0        4.5       18.30  ...        23  0.0500     0           0   
1        9.2       17.84  ...        42  0.0469     1           0   
2        5.6       17.37  ...        39  0.0438     0           0   
3        7.2        8.60  ...        56  0.0407     0           0   
4        4.5        8.60  ...        45  0.0376     0           0   

   airport_Yes  waterbody_Lake  waterbody_Lake & River  waterbody_River  \
0            1               1                       1                0   
1            1               0                       1                1   
2            1               1                       1                1   
3            1               0                       1                1   
4            1               0                       1                1   

   bus_ter_No  bus_ter_Yes  
0           0            1  
1           1            0  
2           0            1  
3           0            1  
4           1            0  

[5 rows x 21 columns]

In [136]:
LX = data.loc[:, data.columns != 'Sold']

In [137]:
LY=data['Sold']

In [138]:
LX.head()

price  resid_area  air_qual  dist1  dist2  dist3  dist4  teachers  \
0   24.0       32.31     0.589      2      2      2    2.0        24   
1   21.6       37.07     0.532      4      2      3    3.0        24   
2   34.7       37.07     0.425      3      2      1    1.0        24   
3   33.4       37.07     0.485      3      2      3    3.0        24   
4   36.9       37.07     0.564      3      3      3    3.0        24   

   poor_prop  n_hos_beds  n_hot_rooms  rainfall   parks  airport_No  \
0        4.5       18.30       11.120        23  0.0500           0   
1        9.2       17.84       12.178        42  0.0469           0   
2        5.6       17.37       12.200        39  0.0438           0   
3        7.2        8.60       10.200        56  0.0407           0   
4        4.5        8.60       10.740        45  0.0376           0   

   airport_Yes  waterbody_Lake  waterbody_Lake & River  waterbody_River  \
0            1               1                       1                0   
1            1               0                       1                1   
2            1               1                       1                1   
3            1               0                       1                1   
4            1               0                       1                1   

   bus_ter_No  bus_ter_Yes  
0           0            1  
1           1            0  
2           0            1  
3           0            1  
4           1            0

In [164]:
LX_filled = LX.fillna(0)

In [165]:
LY.head()

0    0
1    1
2    0
3    0
4    0
Name: Sold, dtype: int64

In [166]:
from sklearn.linear_model import LogisticRegression

In [167]:
clfs_lrsL=LogisticRegression()

In [170]:
from sklearn.preprocessing import LabelEncoder

In [171]:
label_encoder = LabelEncoder()

In [177]:
LX_encoded = LX_filled.apply(label_encoder.fit_transform)

In [178]:
clfs_lrsL.fit(LX_encoded, LY)

C:\Users\divya.sunil\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [179]:
clfs_lrsL.coef_

array([[-0.02217861, -0.07212687,  0.02516111,  0.09898149, -0.19074011,
         0.04685797,  0.03426982, -0.20744559,  0.05633949, -0.03092655,
         0.01534658, -0.04722472, -0.01542165,  0.1479223 , -0.09019378,
         0.45127478, -0.07301278, -0.03058918,  0.11167349, -0.05394497]])

In [180]:
clfs_lrsL.intercept_

array([0.07776087])

In [185]:
LX_const=sn.add_constant(LX_encoded)

In [186]:
LX_const.head()

const  price  resid_area  air_qual  dist1  dist2  dist3  dist4  teachers  \
0    1.0     12           0         6      0      0      1      1         3   
1    1.0      8           2         3      2      0      2      3         3   
2    1.0     20           2         1      1      0      0      0         3   
3    1.0     19           2         2      1      0      2      3         3   
4    1.0     22           2         5      1      1      2      3         3   

   poor_prop  ...  n_hot_rooms  rainfall  parks  airport_No  airport_Yes  \
0          8  ...           34         0     10           0            1   
1         26  ...           43         6      9           0            1   
2         17  ...           44         5      8           0            1   
3         21  ...           29        16      7           0            1   
4          8  ...           33         8      6           0            1   

   waterbody_Lake  waterbody_Lake & River  waterbody_River  bus_ter_No  \
0               1                       1                0           0   
1               0                       1                1           1   
2               1                       1                1           0   
3               0                       1                1           0   
4               0                       1                1           1   

   bus_ter_Yes  
0            1  
1            0  
2            1  
3            1  
4            0  

[5 rows x 21 columns]

In [187]:
import statsmodels.discrete.discrete_model as sm

In [188]:
logit = sm.Logit(LY,LX_const).fit()

Optimization terminated successfully.
         Current function value: 0.641747
         Iterations 6


In [189]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  100
Model:                          Logit   Df Residuals:                       81
Method:                           MLE   Df Model:                           18
Date:                Tue, 07 May 2024   Pseudo R-squ.:                 0.06986
Time:                        12:28:58   Log-Likelihood:                -64.175
converged:                       True   LL-Null:                       -68.994
Covariance Type:            nonrobust   LLR p-value:                    0.9430
==========================================================================================
                             coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------
const                     -0.0557        nan        nan        nan         nan         nan
price                     -0.0241      0.034     -0.715      0.474      -0.090       0.042
resid_area                -0.0838      0.253     -0.331      0.741      -0.580       0.413
air_qual                   0.0346      0.116      0.297      0.766      -0.193       0.263
dist1                      0.1212      0.325      0.373      0.710      -0.517       0.759
dist2                     -0.2559      0.504     -0.508      0.612      -1.244       0.732
dist3                      0.0455      0.241      0.189      0.850      -0.427       0.518
dist4                      0.0351      0.167      0.210      0.834      -0.292       0.363
teachers                  -0.2231      0.213     -1.047      0.295      -0.641       0.195
poor_prop                  0.0573      0.032      1.793      0.073      -0.005       0.120
n_hos_beds                -0.0313      0.027     -1.175      0.240      -0.083       0.021
n_hot_rooms                0.0160      0.014      1.181      0.237      -0.011       0.043
rainfall                  -0.0465      0.039     -1.195      0.232      -0.123       0.030
parks                     -0.0161      0.014     -1.119      0.263      -0.044       0.012
airport_No                 0.1200   1.44e+07   8.32e-09      1.000   -2.83e+07    2.83e+07
airport_Yes               -0.1758   1.44e+07  -1.22e-08      1.000   -2.81e+07    2.81e+07
waterbody_Lake             0.6479      0.713      0.909      0.363      -0.749       2.045
waterbody_Lake & River     0.0178      0.818      0.022      0.983      -1.586       1.621
waterbody_River            0.0981      0.732      0.134      0.893      -1.336       1.532
bus_ter_No                 0.0690   2.11e+07   3.27e-09      1.000   -4.14e+07    4.14e+07
bus_ter_Yes               -0.1248   2.11e+07  -5.91e-09      1.000   -4.14e+07    4.14e+07
==========================================================================================
"""