In [11]:
import numpy

In [12]:
x=numpy.array([11,22,33,44])

In [13]:
x

array([11, 22, 33, 44])

In [14]:
print(x)

[11 22 33 44]


In [15]:
import numpy as np

In [16]:
y=np.array([100,200,300])

In [17]:
y

array([100, 200, 300])

In [18]:
np.__version__

'1.26.4'

In [20]:
z=np.array((44,55,77,88,111))

In [21]:
z

array([ 44,  55,  77,  88, 111])

In [24]:
x2d=np.array([[1,2,3],[55,77,88]])

In [25]:
x2d

array([[ 1,  2,  3],
       [55, 77, 88]])

In [38]:
y2d=np.array([[1,2,3],[22,44,66],[11,33,55]])

In [28]:
y2d

array([[ 1,  2,  3],
       [22, 44, 66],
       [11, 33, 55]])

In [29]:
z1=np.array(55)

In [30]:
z1

array(55)

In [31]:
print(z1)

55


In [33]:
z1.ndim

0

In [39]:
y2d.ndim

2

In [35]:
x2d.ndim

2

In [40]:
q1=np.array([[[1,2,3],[7,8,9],[3,4,5],[6,11,21]]])

In [41]:
q1

array([[[ 1,  2,  3],
        [ 7,  8,  9],
        [ 3,  4,  5],
        [ 6, 11, 21]]])

In [42]:
q1.ndim

3

In [43]:
x

array([11, 22, 33, 44])

In [44]:
x[2]

33

In [45]:
y2d[0,2]

3

In [47]:
y2d[2,2]

55

In [48]:
w=np.array([[[11,21,31],[17,18,19],[32,43,53],[61,11,21]]])

In [49]:
w

array([[[11, 21, 31],
        [17, 18, 19],
        [32, 43, 53],
        [61, 11, 21]]])

In [51]:
q1[0,1,2]

9

In [55]:
w[0,1,1]

18

In [56]:
w[0,2,2]

53