In [186]:
# task 85

In [324]:
import numpy as np
import pandas as pd
import seaborn as sns

In [325]:
movie=pd.read_csv("movielist.csv")

In [326]:
movie.describe()

AudienceScore  TheatersOpenWeek  OpeningWeekend  BOAvgOpenWeekend  \
count      49.000000         48.000000       49.000000         48.000000   
mean       72.408163       3208.000000       39.783673      11795.875000   
std        12.037993        782.484586       30.031389       6600.083025   
min        47.000000        860.000000        6.500000       2641.000000   
25%        64.000000       2921.500000       21.900000       7596.500000   
50%        73.000000       3390.000000       33.000000      10055.500000   
75%        83.000000       3677.500000       45.300000      12811.500000   
max        91.000000       4362.000000      151.100000      35540.000000   

       DomesticGross  ForeignGross  WorldGross      Budget  Profitability  \
count      49.000000     49.000000   49.000000   49.000000      49.000000   
mean      134.190612    164.390204  298.580204   87.622449     452.997143   
std        81.884008    162.097937  235.719684   64.478237     446.667424   
min        47.850000      0.660000   55.860000    7.500000      99.100000   
25%        66.660000     63.640000  147.880000   33.000000     238.870000   
50%       118.590000     97.340000  202.550000   75.000000     366.250000   
75%       168.270000    215.350000  372.230000  130.000000     516.190000   
max       336.530000    654.000000  963.420000  300.000000    3085.480000   

       OpenProfit  Current Year      Oscar  
count   49.000000     49.000000  49.000000  
mean    63.389796      0.448980   0.469388  
std     53.955310      0.502545   0.504234  
min     12.800000      0.000000   0.000000  
25%     31.330000      0.000000   0.000000  
50%     43.600000      0.000000   0.000000  
75%     76.000000      1.000000   1.000000  
max    317.000000      1.000000   1.000000

In [327]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Movie             49 non-null     object 
 1   AudienceScore     49 non-null     int64  
 2   TheatersOpenWeek  48 non-null     float64
 3   OpeningWeekend    49 non-null     float64
 4   BOAvgOpenWeekend  48 non-null     float64
 5   DomesticGross     49 non-null     float64
 6   ForeignGross      49 non-null     float64
 7   WorldGross        49 non-null     float64
 8   Budget            49 non-null     float64
 9   Profitability     49 non-null     float64
 10  OpenProfit        49 non-null     float64
 11  Current Year      49 non-null     int64  
 12  Oscar             49 non-null     int64  
dtypes: float64(9), int64(3), object(1)
memory usage: 5.1+ KB


In [328]:
movie.head()

Movie  AudienceScore  TheatersOpenWeek  \
0                               Spider-Man 3             54            4252.0   
1                            Shrek the Third             57            4122.0   
2                               Transformers             89            4011.0   
3   Pirates of the Caribbean: At World's End             74            4362.0   
4  Harry Potter and the Order of the Phoenix             82            4285.0   

   OpeningWeekend  BOAvgOpenWeekend  DomesticGross  ForeignGross  WorldGross  \
0           151.1           35540.0         336.53        554.34      890.87   
1           121.6           29507.0         322.72        476.24      798.96   
2            70.5           17577.0         319.25        390.46      709.71   
3           114.7           26302.0         309.42        654.00      963.42   
4            77.1           17998.0         292.00        647.88      939.89   

   Budget  Profitability  OpenProfit  Current Year  Oscar  
0   258.0         345.30       58.57             1      0  
1   160.0         499.35       76.00             0      1  
2   150.0         473.14       47.00             1      0  
3   300.0         321.14       38.23             0      0  
4   150.0         626.59       51.40             1      0

In [329]:
movie.head()

Movie  AudienceScore  TheatersOpenWeek  \
0                               Spider-Man 3             54            4252.0   
1                            Shrek the Third             57            4122.0   
2                               Transformers             89            4011.0   
3   Pirates of the Caribbean: At World's End             74            4362.0   
4  Harry Potter and the Order of the Phoenix             82            4285.0   

   OpeningWeekend  BOAvgOpenWeekend  DomesticGross  ForeignGross  WorldGross  \
0           151.1           35540.0         336.53        554.34      890.87   
1           121.6           29507.0         322.72        476.24      798.96   
2            70.5           17577.0         319.25        390.46      709.71   
3           114.7           26302.0         309.42        654.00      963.42   
4            77.1           17998.0         292.00        647.88      939.89   

   Budget  Profitability  OpenProfit  Current Year  Oscar  
0   258.0         345.30       58.57             1      0  
1   160.0         499.35       76.00             0      1  
2   150.0         473.14       47.00             1      0  
3   300.0         321.14       38.23             0      0  
4   150.0         626.59       51.40             1      0

In [330]:
movie=movie.iloc[:50]

In [331]:
movie=movie.replace({True: 1, False: 0})

In [332]:
movie.head()

Movie  AudienceScore  TheatersOpenWeek  \
0                               Spider-Man 3             54            4252.0   
1                            Shrek the Third             57            4122.0   
2                               Transformers             89            4011.0   
3   Pirates of the Caribbean: At World's End             74            4362.0   
4  Harry Potter and the Order of the Phoenix             82            4285.0   

   OpeningWeekend  BOAvgOpenWeekend  DomesticGross  ForeignGross  WorldGross  \
0           151.1           35540.0         336.53        554.34      890.87   
1           121.6           29507.0         322.72        476.24      798.96   
2            70.5           17577.0         319.25        390.46      709.71   
3           114.7           26302.0         309.42        654.00      963.42   
4            77.1           17998.0         292.00        647.88      939.89   

   Budget  Profitability  OpenProfit  Current Year  Oscar  
0   258.0         345.30       58.57             1      0  
1   160.0         499.35       76.00             0      1  
2   150.0         473.14       47.00             1      0  
3   300.0         321.14       38.23             0      0  
4   150.0         626.59       51.40             1      0

In [333]:
X=movie[['Budget']]

In [334]:
Y=movie[['Oscar']]

In [335]:
X.head()

Budget
0   258.0
1   160.0
2   150.0
3   300.0
4   150.0

In [336]:
Y.head()

Oscar
0      0
1      1
2      0
3      0
4      0

In [337]:
X=X.fillna(0)
Y=Y.fillna(0)

In [338]:
from sklearn.linear_model import LogisticRegression

In [339]:
clfs_lrs=LogisticRegression()

In [340]:
clfs_lrs.fit(X,Y)

C:\Users\divya.sunil\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [341]:
clfs_lrs.coef_

array([[-0.00555668]])

In [342]:
clfs_lrs.intercept_

array([0.35708087])

In [343]:
import statsmodels.api as sn

In [344]:
X_const=sn.add_constant(X)

In [345]:
X_const.head()

const  Budget
0    1.0   258.0
1    1.0   160.0
2    1.0   150.0
3    1.0   300.0
4    1.0   150.0

In [346]:
import statsmodels.discrete.discrete_model as sm

In [347]:
logit = sm.Logit(Y,X_const).fit()

Optimization terminated successfully.
         Current function value: 0.676749
         Iterations 4


In [348]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                  Oscar   No. Observations:                   49
Model:                          Logit   Df Residuals:                       47
Method:                           MLE   Df Model:                            1
Date:                Wed, 08 May 2024   Pseudo R-squ.:                 0.02101
Time:                        13:40:59   Log-Likelihood:                -33.161
converged:                       True   LL-Null:                       -33.872
Covariance Type:            nonrobust   LLR p-value:                    0.2329
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.3571      0.500      0.714      0.475      -0.623       1.337
Budget        -0.0056      0.005     -1.155      0.248      -0.015       0.004
==============================================================================
"""

In [212]:
#Task 88

In [414]:
movie=pd.read_csv("movielist.csv")

In [415]:
movie=movie.head(50)

In [416]:
movie = pd.get_dummies(movie,columns=['Current Year'])

In [417]:
movie = movie.replace({True: 0, False: 1})

In [418]:
movie.head()

Movie  AudienceScore  TheatersOpenWeek  \
0                               Spider-Man 3             54            4252.0   
1                            Shrek the Third             57            4122.0   
2                               Transformers             89            4011.0   
3   Pirates of the Caribbean: At World's End             74            4362.0   
4  Harry Potter and the Order of the Phoenix             82            4285.0   

   OpeningWeekend  BOAvgOpenWeekend  DomesticGross  ForeignGross  WorldGross  \
0           151.1           35540.0         336.53        554.34      890.87   
1           121.6           29507.0         322.72        476.24      798.96   
2            70.5           17577.0         319.25        390.46      709.71   
3           114.7           26302.0         309.42        654.00      963.42   
4            77.1           17998.0         292.00        647.88      939.89   

   Budget  Profitability  OpenProfit  Oscar  Current Year_0  Current Year_1  
0   258.0         345.30       58.57      0               1               0  
1   160.0         499.35       76.00      1               0               1  
2   150.0         473.14       47.00      0               1               0  
3   300.0         321.14       38.23      0               0               1  
4   150.0         626.59       51.40      0               1               0

In [419]:
LX = movie.loc[:, movie.columns != 'Oscar']

In [420]:
LY=movie['Oscar']

In [423]:
LX.head()

Movie  AudienceScore  TheatersOpenWeek  \
0                               Spider-Man 3             54            4252.0   
1                            Shrek the Third             57            4122.0   
2                               Transformers             89            4011.0   
3   Pirates of the Caribbean: At World's End             74            4362.0   
4  Harry Potter and the Order of the Phoenix             82            4285.0   

   OpeningWeekend  BOAvgOpenWeekend  DomesticGross  ForeignGross  WorldGross  \
0           151.1           35540.0         336.53        554.34      890.87   
1           121.6           29507.0         322.72        476.24      798.96   
2            70.5           17577.0         319.25        390.46      709.71   
3           114.7           26302.0         309.42        654.00      963.42   
4            77.1           17998.0         292.00        647.88      939.89   

   Budget  Profitability  OpenProfit  Current Year_0  Current Year_1  
0   258.0         345.30       58.57               1               0  
1   160.0         499.35       76.00               0               1  
2   150.0         473.14       47.00               1               0  
3   300.0         321.14       38.23               0               1  
4   150.0         626.59       51.40               1               0

In [396]:
LX_filled = LX.fillna(0)

In [424]:
LX_filled.tail()

Movie  AudienceScore  \
44                                    3:10 to Yuma             85   
45  Sweeney Todd: The Demon Barber of Fleet Street             81   
46                                Music and Lyrics             70   
47                                 Michael Clayton             72   
48                                     Premonition             55   

    TheatersOpenWeek  OpeningWeekend  BOAvgOpenWeekend  DomesticGross  \
44            2652.0            14.0            5292.0          53.61   
45            1249.0             9.3            7446.0          52.90   
46               0.0            13.6               0.0          50.57   
47            2511.0            10.4            4131.0          49.03   
48            2831.0            17.6            6202.0          47.85   

    ForeignGross  WorldGross  Budget  Profitability  OpenProfit  \
44         16.41       70.02    48.0         145.86       29.17   
45         99.63      152.52    50.0         305.05       18.60   
46         95.32      145.90    40.0         364.74       34.00   
47         43.96       92.99    25.0         371.96       41.60   
48         36.29       84.15    20.0         420.73       88.00   

    Current Year_0  Current Year_1  
44               0               1  
45               0               1  
46               0               1  
47               1               0  
48               0               1

In [425]:
LY.head()

0    0
1    1
2    0
3    0
4    0
Name: Oscar, dtype: int64

In [431]:
from sklearn.linear_model import LogisticRegression

In [432]:
clfs_lrsL=LogisticRegression()

In [433]:
from sklearn.preprocessing import LabelEncoder

In [434]:
label_encoder = LabelEncoder()

In [435]:
LX_encoded = LX_filled.apply(label_encoder.fit_transform)

In [436]:
clfs_lrsL.fit(LX_encoded,LY)

C:\Users\divya.sunil\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [437]:
clfs_lrsL.coef_

array([[-0.00152199, -0.03046282,  0.03826291, -0.09436143,  0.13883087,
        -0.0155944 ,  0.01110839, -0.14905239,  0.10499101,  0.11339353,
        -0.10352372,  0.68403512, -0.6659846 ]])

In [438]:
clfs_lrsL.intercept_

array([0.02388089])

In [439]:
LX_const=sn.add_constant(LX_encoded)

In [440]:
LX_const.head()

const  Movie  AudienceScore  TheatersOpenWeek  OpeningWeekend  \
0    1.0     35              2                44              44   
1    1.0     34              5                43              43   
2    1.0     46             25                42              37   
3    1.0     29             14                46              42   
4    1.0     15             19                45              40   

   BOAvgOpenWeekend  DomesticGross  ForeignGross  WorldGross  Budget  \
0                48             48            46          46      29   
1                47             47            45          45      26   
2                40             46            43          44      25   
3                46             45            48          48      30   
4                41             44            47          47      25   

   Profitability  OpenProfit  Current Year_0  Current Year_1  
0             20          32               1               0  
1             35          36               0               1  
2             34          27               1               0  
3             19          17               0               1  
4             40          28               1               0

In [441]:
import statsmodels.discrete.discrete_model as sm

In [445]:
logit = sm.Logit(LY,LX_const).fit()

Optimization terminated successfully.
         Current function value: 0.549331
         Iterations 6


In [446]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                  Oscar   No. Observations:                   49
Model:                          Logit   Df Residuals:                       36
Method:                           MLE   Df Model:                           12
Date:                Wed, 08 May 2024   Pseudo R-squ.:                  0.2053
Time:                        13:57:44   Log-Likelihood:                -26.917
converged:                       True   LL-Null:                       -33.872
Covariance Type:            nonrobust   LLR p-value:                    0.3065
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.4061        nan        nan        nan         nan         nan
Movie                0.0005      0.028      0.017      0.987      -0.054       0.055
AudienceScore       -0.0371      0.070     -0.531      0.595      -0.174       0.100
TheatersOpenWeek     0.0350      0.072      0.486      0.627      -0.106       0.176
OpeningWeekend      -0.0785      0.171     -0.459      0.646      -0.414       0.257
BOAvgOpenWeekend     0.1388      0.103      1.351      0.177      -0.063       0.340
DomesticGross       -0.0129      0.116     -0.111      0.911      -0.240       0.214
ForeignGross         0.0086      0.123      0.070      0.945      -0.233       0.250
WorldGross          -0.1507      0.176     -0.856      0.392      -0.496       0.194
Budget               0.0792      0.252      0.314      0.753      -0.415       0.573
Profitability        0.1168      0.090      1.296      0.195      -0.060       0.293
OpenProfit          -0.1204      0.106     -1.138      0.255      -0.328       0.087
Current Year_0       1.0438        nan        nan        nan         nan         nan
Current Year_1      -0.6377        nan        nan        nan         nan         nan
====================================================================================
"""